#!/usr/bin/zsh

TARGET=$1
if [ "$TARGET" = "" ] ; then
  echo usage: $0 TARGET
fi

if [ -f cidfile ] ; then
  podman cp $(cat cidfile):.local/share/factorio/saves/default.zip $TARGET
else
  echo error: no cidfile
  exit 1
fi

